// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    VApp: typeof import('vuetify/lib')['VApp']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VDialog: typeof import('vuetify/lib')['VDialog']
  }
}

export { }
