version: "3.7"
services:
  node:
    container_name: node
    image: node:16
    restart: unless-stopped
    command: "/bin/bash -c \"trap : TERM INT; sleep infinity & wait\""
    user: "${UID:-1000}"
    volumes:
      - type: bind
        source: ./
        target: /app